### ISSUE TITLE
`R2.scaleLiability(...)` produces  `NA`

### ISSUE THREAD

**Issue by espenhgn** [deepchocolate/glm-extras#1]
Hi @deepchocolate, 
I've been testing these codes and encountered some issue. 
My procedure is similar to the examples you provide in the readme, however, I have to exclude some NaNs when fitting the `glm`, e.g.:
```
linear.fit <- glm(reg.formula, data=train, family=binomial, na.action=na.exclude)
mR2 <- R2Wrap(linear.fit)
R2.scaleLiability(mR2, 0.01)
```
which gives `NA`. Is that to be expected in the current version of these codes?
It works without `na.action=na.exclude`, though, so I may have to drop some rows in the dataset prior to invoking the glm.

`linear.fit` object:
<img width="742" alt="image" src="https://github.com/deepchocolate/glm-extras/assets/2492641/92ad9884-321a-4267-bc52-21433738cd52">
`mR2` object:
<img width="748" alt="image" src="https://github.com/deepchocolate/glm-extras/assets/2492641/db7cb6de-72c9-4dc0-9460-c28fc4112b6c">

**Comment by deepchocolate** [comment]
@espenhgn 
Missing values is not something I've about at all unfortunately. But I should add an exception indicating that missingness is a problem. I think the default of `glm` is `glm(..., na.action=na.omit,...)`, and that will exclude NAs in the predictions that are used to calculate liability R2, so I guess that's why it's working when you don't use `na.exclude`. I will look more into it when I'm back from vacation

**Comment by espenhgn** [comment]
Hi, no worries. This could be worked around quite easily. Enjoy your holiday!
